/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "default": {
      "type": "sst.aws.Vpc"
    }
    "graphql-http": {
      "name": string
      "type": "sst.aws.Function"
    }
    "graphql-ws": {
      "name": string
      "type": "sst.aws.Function"
    }
    "http": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "redis": {
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Redis"
      "username": string
    }
    "shared": {
      "region": string
      "type": "sst.sst.Linkable"
    }
    "ws": {
      "managementEndpoint": string
      "type": "sst.aws.ApiGatewayWebSocket"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}